name: CI 

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    # Restore from cache the previously built ports. If cache-miss, download, build vcpkg.
    - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v3
      with:
        setupOnly: true
    # Now that vcpkg is installed, it is being used to run desired arguments.
    - run: |
        brew install pkg-config
        $VCPKG_ROOT/vcpkg @$vcpkgResponseFile
        $VCPKG_ROOT/vcpkg install tinyxml2 zlib libpng libjpeg-turbo icu
      shell: bash
    - name: install qt
      run: |
        brew update
        brew install qt
    - name: release build
      run: ./scripts/build_mac.sh
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      with:
        name: PSDtoSS6-${{ matrix.platform }}-${{ github.sha }}
        path: out
  win_build:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: prepare build environment
      shell: cmd
      run: scripts\prepare_win.bat
    - name: install cmake
      run: |
        curl -O https://cmake.org/files/v3.15/cmake-3.15.5-win64-x64.zip
        7z x cmake-3.15.5-win64-x64.zip -oC:\projects\deps
        move C:\projects\deps\cmake-* C:\projects\deps\cmake
        $env:Path = "C:\projects\deps\cmake\bin" + ";" + $env:Path
        cmake --version
        cmake -h
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
    - name: "set QT_PREFIX"
      run: $env:QT_PREFIX = $env:Qt5_Dir
    - name: release build
      shell: cmd
      run: Scripts\build_win.bat
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      with:
        name: PSDtoSS6-${{ matrix.platform }}-${{ github.sha }}
        path: out
