name: CI 

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run brew install pkg-config
      run: |
        brew update
        brew install pkg-config        
    # Restore from cache the previously built ports. If cache-miss, download, build vcpkg.
    - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v3
      with:
        vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
      env:
        vcpkgResponseFile: '${{ github.workspace }}/response_file_mac.txt'
    - name: install qt
      run: |
        brew install qt
    - name: release build
      run: ./scripts/build_mac.sh
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      with:
        name: PSDtoSS6-${{ matrix.platform }}-${{ github.sha }}
        path: out
  win_build:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Get latest CMake
      uses: lukka/get-cmake@latest
    - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v3
      with:
        vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
      env:
        vcpkgResponseFile: '${{ github.workspace }}/response_file_win.txt'
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
    - name: "set QT_PREFIX"
      run: $env:QT_PREFIX = $env:Qt5_Dir
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: release build
      shell: cmd
      run: Scripts\build_win.bat
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      with:
        name: PSDtoSS6-${{ matrix.platform }}-${{ github.sha }}
        path: out
