name: CI

on: [push]

jobs:
  win_build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: prepare build environment
      shell: cmd
      run: scripts\prepare_win.bat
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: "npm ci"
      run: npm ci
    - name: "npm run build"
      run: npm run build      
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
          path: ../Qt
          key: QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: "set QT_PREFIX"
      run: $env:QT_PREFIX = $env:Qt5_Dir
    - name: release build
      shell: cmd
      run: Scripts\build_win.bat
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      with:
        name: PSDtoSS6-${{ matrix.platform }}-${{ github.sha }}
        path: out
    - name: install cmake
      run: |
        curl -O https://cmake.org/files/v3.15/cmake-3.15.5-win64-x64.zip
        7z x cmake-3.15.5-win64-x64.zip -oC:\projects\deps
        move C:\projects\deps\cmake-* C:\projects\deps\cmake
        $env:Path = "C:\projects\deps\cmake\bin" + ";" + $env:Path
        cmake --version
        cmake -h
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: prepare build environment
      run: ./scripts/prepare_mac.sh
    - name: install qt
      run: |
        brew update
        brew install qt
    - name: release build
      run: ./scripts/build_mac.sh
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      with:
        name: PSDtoSS6-${{ matrix.platform }}-${{ github.sha }}
        path: out
